name: CI

on:
  push:
    branches: [master]
  pull_request:

env:
  DOTNET_NOLOGO: true
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
        matrix:
            os: [macOS-latest, ubuntu-latest, windows-latest]

    steps:
    - uses: actions/checkout@v4.2.2
    - name: Setup .NET
      uses: actions/setup-dotnet@v4.3.0
      with:
        dotnet-version: '8.0.x'
    - name: Build with dotnet
      run: dotnet build --configuration Release src/TextEdit/ImGuiColorTextEditNet.csproj
    - name: Test with dotnet
      run: dotnet test TextEdit.sln --configuration Release

